### ISSUE TITLE
测试的一些小问题并开始准备进行数据库操作

### ISSUE THREAD

**Issue by jiminHuang** [tothemoon96/simple_stock_crawler#5]
- test_stock_price.py
  - 59行 建议使用nose.tools中的assert_equals代替assert cmp
  - 69-78行 提交时去除不需要的代码注释
- 设计并建立测试数据库
  - 根据提取目标的结构化对象设计在数据库中的表
  - 建立一个测试数据库
  - 了解并开始使用sqlalchemy连接python数据库

**Comment by tothemoon96** [comment]
添加连接数据库的工具database.py
添加读取外部配置文件的工具config.py
添加了对这两个文件的测试

添加了data.py、pipeline.py，还没有完成这两个文件的单元测试
一个能够向数据库写入爬取的数据的初步版本

**Comment by jiminHuang** [comment]
- 建立表持久化对象的测试
  - 注意单元测试与功能测试的区别
  - 数据库这里我们需要功能测试而不是单元测试，即我们需要实际连接一个数据库，比如说我们自己建立的测试数据库来测试与数据库的操作是否能正常进行
- conf文件夹里的yaml是你的配置文件 **不要上传** 这非常危险 你在暴露你的数据库连接的全部信息
- database.py
  - 行6 这样script的写法会使得你的功能测试非常困难
  - 行10-14 缩进
  - 行17 不必要的空行
  - 行25 这样虽然避免了过长 但是可读性比较差
  - 行43 这里已经捕获了数据库异常 但是并不会继续抛出异常到上层
- test_database.py
  - 行57-77 个人认为这个测试毫无意义 这实际上没有测试你写的任何代码
- test_cofig.py
  - 文件名有错误
- data.py
  - 行3-7 可以一起import进来 不仅更有效率且更美观
  - 行11 这里应该有两个空行
  - 行37 这个封装毫无意义
    - 没有利用到持久化对象，如果还是使用传入参数进行操作的话
    - 行47catch不到任何的异常 因为都在DBConnection的__exit__中被捕获了 这意味着你之后的所有操作都不会执行
    - 你在这里的操作有点太多了 except中如果还有try 那么一定要考虑是不是思路有问题
- pipelines.py
  - 行8 无必要的空行
